name: Update RSS Feed

on:
  schedule:
    - cron: "0 */6 * * *"  # alle 6 Stunden
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch and cache RSS feed
        run: |
          curl -s https://api.rss2json.com/v1/api.json?rss_url=https://feeds.macrumors.com/MacRumors-All \
          -o feed.json
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add feed.json
          git commit -m "Update RSS feed"
          git push
